# Generated by Django 6.1.1 on 2026-09-16 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('assign', 'Assign'), ('status_change', 'Status Change'), ('member_add', 'Member Added'), ('member_remove', 'Member Removed'), ('role_change', 'Role Changed')], max_length=30)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='audit_audit_workspa_e79ba8_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx')],
            },
        ),
    ]
