# Generated by Django 6.1.1 on 2026-09-16 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#808080', help_text='Hex color, e.g. #FF5733', max_length=7)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
